[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.flash_size = 4MB

lib_deps =
  bblanchon/ArduinoJson@^6.21.5

build_flags =
  -DCORE_DEBUG_LEVEL=1

; OTA upload environment.
; Usage: pio run -e ota --target upload --upload-port <ESP_IP>
; Example: pio run -e ota --target upload --upload-port 192.168.1.100
[env:ota]
platform = espressif32
board = esp32dev
framework = arduino
board_build.flash_size = 4MB
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=1
upload_protocol = espota
upload_port = 192.168.1.100
upload_flags =
  --auth=